config/routes.rb
Rails.application.routes.draw do
  
  resources :posts

   root      'posts#index'

  get 'about' => 'home#about'
  get 'contact' => 'home#contact'

end

app/models/entry.rb
class Entry < ActiveRecord::Base

	
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entry_controller.rb
class EntryController < ApplicationController

	def index

  	end
  
  

  	def new

  	end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index


  end


def about


  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController


	def index
	
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		@post.save
		redirect_to @post
	end

	def show
		@post = Post.find(params[:id])
	end

	private
		def post_params
			params.require(:post).permit(:title, :body)
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entry_helper.rb
module EntryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/entry/index.html.erb
<h1>
Welcome to myPost Index. This is that index.html.erb
</h1>

app/views/entry/new.html.erb
<div id="page_wrapper">
<h1>New Post</h1>
<p>Ready for your next blog entry? Take it away. </p><br>

<%= form_for :Post, url: newentry_path do |f| %>
<p>
	<%= f.label :title %>
	<%= f.text_field :title %>
</p>
<p>
<br>

	<%= f.label :body %>
	<%= f.text_area :body %>
</p>

<p>
	<%= f.submit %>

</p>


<% end %>

</div>

app/views/home/about.html.erb
<div id="page_wrapper">
<h1> About this  </h1>
<p>
This is my first demo app for submission. Feel free to email me for feedback. Thanks for dropping by! 
</p>
</div>

app/views/home/contact.html.erb
<div id="page_wrapper">
<h1>Contact Me </h1>
<p>
I would like to hear from you. Write a feedback about this project. Drop me an email at grace.m.sojor@framgia.com. 
</p>

</div>

app/views/home/index.html.erb
<div class="center jumbotron">

</div>


<h1>Welcome to BlogMe App</h1>
<h2>This is the homepage for this demo app.</h2>

<%= link_to "Sign up Now!", "#", class: "btn btn-lg btn-primary" %>

app/views/layouts/_footer.html.erb
<footer class= "footer">

	<small>
	Demo App Project by Grace Sojor
	</small>
	
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class ="container">
		<%= link_to "BlogMe","#", id: "logo" %>
			<nav>
				<ul class ="nav bar navbar-nav pull-right">
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "About", about_path %></li>
				<li><%= link_to "New Post", new_path %></li>
				<li><%= link_to "Login", '#' %></li>
			</ul>
			</nav>
</header> 

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogme</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

   <%= render 'layouts/shim' %>

</head>
<body>


<div id="sidebar">
	<div id="logo">
		<%= link_to root_path do %>
		<%= image_tag "logoblog.png" %>
		<% end %>

		<ul>
		<li class ="category"> Project Description </li>
		<li><%= link_to "About", about_path %></li>
		</ul>

		<ul>
		<li class ="category"> About the Writer </li>
		<li><%= link_to "Contact", contact_path %></li>
		<li class ="sign_in"> Admin Login </li>
		</ul>




<!---sign in nav 
<div style="padding-bottom: 55px;" id="main-nav">

<ul id="navigation" class=""><li base-menu="1" id="menu-item-428" class="menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-2 current_page_item menu-item-428"><a href="#"><i class="fa-home fa"></i><span class="fontawesome-text"> Admin Login</span></a></li>

<li id="menu-item-459" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-459"><a href="#/contact/"><i class="fa-user fa"></i><span class="fontawesome-text"> Contact</span></a></li>
</ul>          </div>

-->

</div>

<div id="main_content">
<div id="header">

	<p>All Post Entries</p>
	<div class="buttons">
		<!--
		<li><!- %= link_to "New Post", new_entry_path, class: "btn btn-default" %></li>
 		<li><!-%= link_to "Log Out", "#", class: "btn btn-default" %></li>
		-->

	</div>

</div>

<%= yield %>

</div>






</body>
</html>

app/views/posts/index.html.erb
<div id="page_wrapper">
<h1>This is Post Index. </h1> </div>

app/views/posts/new.html.erb
<div id="page_wrapper">

<h1>New Post</h1>
<p>Ready for your next blog entry? Take it away. </p><br>

<%= form_for @post do |f| %>
	<p>
		<%= f.label :title %>
		<br>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :body %>
		<br>
		<%= f.text_area :body %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

</div>

app/views/posts/show.html.erb
<h1 class="title">
<%= @post.title %>

</h1>

<p class="date">
	Submitted <%= time_ago_in_words(@post.created_at) %> Ago
</p>

<p class="body"> <%= @post.body %> </p>